/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#f9f9fc',
        'on-background': '#1a1c1e',
        surface: '#f9f9fc',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#404945',
        'surface-variant': '#e2e2e5',
        'surface-dim': '#dadadc',
        'surface-bright': '#f9f9fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f6',
        'surface-container': '#eeeef0',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e5',
        'inverse-surface': '#2f3133',
        'inverse-on-surface': '#f0f0f3',
        outline: '#717975',
        'outline-variant': '#c0c8c3',
        'surface-tint': '#3a6758',
        
        primary: '#134235',
        'on-primary': '#ffffff',
        'primary-container': '#2d5a4c',
        'on-primary-container': '#a0cfbe',
        'inverse-primary': '#a1d1bf',
        'primary-fixed': '#bcedda',
        'primary-fixed-dim': '#a1d1bf',
        'on-primary-fixed': '#002118',
        'on-primary-fixed-variant': '#214f41',
        
        secondary: '#2b6957',
        'on-secondary': '#ffffff',
        'secondary-container': '#b0f0d8',
        'on-secondary-container': '#316f5d',
        'secondary-fixed': '#b0f0d8',
        'secondary-fixed-dim': '#95d3bd',
        'on-secondary-fixed': '#002118',
        'on-secondary-fixed-variant': '#0a5040',
        
        tertiary: '#2d3f38',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#44564e',
        'on-tertiary-container': '#b6cac0',
        'tertiary-fixed': '#d3e7dd',
        'tertiary-fixed-dim': '#b7cbc1',
        'on-tertiary-fixed': '#0e1f19',
        'on-tertiary-fixed-variant': '#394b43',
        
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        
        'calm-green': '#4a7c59',
        'calm-amber': '#c28b47',
        'calm-terracotta': '#b85c4b',
        'mineral-slate': '#7b8e85',
      },
      fontFamily: {
        sans: ['Geist', 'sans-serif'],
        headline: ['Geist', 'sans-serif'],
        body: ['Geist', 'sans-serif'],
        label: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '500' }],
        'display-lg-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['17px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
